accounts:
  - name: alice
    coins: ["1000token", "100000000stake"]
  - name: bob
    coins: ["500token"]
validator:
  name: alice
  staked: "100000000stake"
faucet:
  name: bob 
  coins:
    - "5token"
genesis:
  chain_id: "jupiter1"
init:
  home: "$HOME/jupiter1"