// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: laugh/genesis.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the laugh module's genesis state.
type GenesisState struct {
	// this line is used by starport scaffolding # genesis/proto/state
	HohoList     []*Hoho     `protobuf:"bytes,7,rep,name=hohoList,proto3" json:"hohoList,omitempty"`
	HihiList     []*Hihi     `protobuf:"bytes,6,rep,name=hihiList,proto3" json:"hihiList,omitempty"`
	HahaList     []*Haha     `protobuf:"bytes,5,rep,name=hahaList,proto3" json:"hahaList,omitempty"`
	HohosentList []*Hohosent `protobuf:"bytes,4,rep,name=hohosentList,proto3" json:"hohosentList,omitempty"`
	HihisentList []*Hihisent `protobuf:"bytes,3,rep,name=hihisentList,proto3" json:"hihisentList,omitempty"`
	HahasentList []*Hahasent `protobuf:"bytes,2,rep,name=hahasentList,proto3" json:"hahasentList,omitempty"`
	PortId       string      `protobuf:"bytes,1,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b2d97a0640f265a, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetHohoList() []*Hoho {
	if m != nil {
		return m.HohoList
	}
	return nil
}

func (m *GenesisState) GetHihiList() []*Hihi {
	if m != nil {
		return m.HihiList
	}
	return nil
}

func (m *GenesisState) GetHahaList() []*Haha {
	if m != nil {
		return m.HahaList
	}
	return nil
}

func (m *GenesisState) GetHohosentList() []*Hohosent {
	if m != nil {
		return m.HohosentList
	}
	return nil
}

func (m *GenesisState) GetHihisentList() []*Hihisent {
	if m != nil {
		return m.HihisentList
	}
	return nil
}

func (m *GenesisState) GetHahasentList() []*Hahasent {
	if m != nil {
		return m.HahasentList
	}
	return nil
}

func (m *GenesisState) GetPortId() string {
	if m != nil {
		return m.PortId
	}
	return ""
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "ltacker.jupiter.laugh.GenesisState")
}

func init() { proto.RegisterFile("laugh/genesis.proto", fileDescriptor_5b2d97a0640f265a) }

var fileDescriptor_5b2d97a0640f265a = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x1b, 0x02, 0x29, 0x84, 0x0e, 0x28, 0x80, 0xa8, 0x40, 0x32, 0x15, 0x53, 0x26, 0x47,
	0x82, 0x81, 0xbd, 0x0c, 0x80, 0xc4, 0x64, 0x36, 0x16, 0xe4, 0xb6, 0x56, 0xee, 0xa0, 0xd4, 0x51,
	0xe2, 0x48, 0xf0, 0x16, 0xbc, 0x02, 0x6f, 0xc3, 0xd8, 0x91, 0x11, 0x25, 0x2f, 0x82, 0x72, 0x31,
	0xa9, 0x52, 0x55, 0x19, 0xf3, 0xeb, 0xfb, 0x7e, 0x5f, 0xee, 0xfc, 0xc3, 0xb9, 0xcc, 0x63, 0x88,
	0x62, 0xb5, 0x50, 0x19, 0x66, 0x3c, 0x49, 0xb5, 0xd1, 0xc1, 0xf1, 0xdc, 0xc8, 0xe9, 0xab, 0x4a,
	0xf9, 0x4b, 0x9e, 0xa0, 0x51, 0x29, 0x27, 0xe8, 0xf4, 0xa0, 0x66, 0x41, 0x83, 0xae, 0xc1, 0x26,
	0x41, 0xc0, 0xb5, 0x44, 0x82, 0xb4, 0xc9, 0xd1, 0xca, 0xca, 0xd4, 0xc2, 0xac, 0xa5, 0x08, 0xb8,
	0x21, 0x95, 0x20, 0x57, 0xe9, 0xc5, 0x97, 0xeb, 0x0f, 0x6e, 0xeb, 0x01, 0x1f, 0x8d, 0x34, 0x2a,
	0xb8, 0xf6, 0x77, 0xab, 0xba, 0x07, 0xcc, 0xcc, 0xb0, 0x3f, 0x72, 0xc3, 0xfd, 0xcb, 0x33, 0xbe,
	0x71, 0x64, 0x7e, 0xa7, 0x41, 0x8b, 0x06, 0x26, 0x11, 0x01, 0x49, 0xf4, 0xba, 0x45, 0x04, 0x14,
	0x0d, 0x4c, 0xa2, 0x04, 0x49, 0xe2, 0x4e, 0xb7, 0x28, 0x41, 0x8a, 0x06, 0x0e, 0x6e, 0xfc, 0xc1,
	0xff, 0x9f, 0x93, 0xbc, 0x4d, 0xf2, 0x79, 0xc7, 0xb8, 0x15, 0x2a, 0x5a, 0x12, 0x95, 0xd8, 0x45,
	0x51, 0x89, 0xdb, 0x5d, 0x62, 0x51, 0xd1, 0x92, 0xa8, 0xc4, 0xee, 0x95, 0x4a, 0xb6, 0xba, 0x4b,
	0x2c, 0x2a, 0x5a, 0x52, 0x70, 0xe2, 0xf7, 0x13, 0x9d, 0x9a, 0x67, 0x9c, 0x0d, 0x9d, 0x91, 0x13,
	0xee, 0x09, 0xaf, 0xfa, 0xbc, 0x9f, 0x8d, 0xc7, 0xdf, 0x05, 0x73, 0x96, 0x05, 0x73, 0x7e, 0x0b,
	0xe6, 0x7c, 0x96, 0xac, 0xb7, 0x2c, 0x59, 0xef, 0xa7, 0x64, 0xbd, 0xa7, 0x30, 0x46, 0x03, 0xf9,
	0x84, 0x4f, 0xf5, 0x5b, 0x64, 0xdf, 0x8a, 0xec, 0x5b, 0xd1, 0x7b, 0x54, 0x1f, 0xdc, 0x7c, 0x24,
	0x2a, 0x9b, 0x78, 0x74, 0xee, 0xab, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x29, 0x87, 0xa3, 0xa7,
	0x94, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.HohoList) > 0 {
		for iNdEx := len(m.HohoList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.HohoList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.HihiList) > 0 {
		for iNdEx := len(m.HihiList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.HihiList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.HahaList) > 0 {
		for iNdEx := len(m.HahaList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.HahaList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.HohosentList) > 0 {
		for iNdEx := len(m.HohosentList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.HohosentList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.HihisentList) > 0 {
		for iNdEx := len(m.HihisentList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.HihisentList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.HahasentList) > 0 {
		for iNdEx := len(m.HahasentList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.HahasentList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.PortId) > 0 {
		i -= len(m.PortId)
		copy(dAtA[i:], m.PortId)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.PortId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PortId)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if len(m.HahasentList) > 0 {
		for _, e := range m.HahasentList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.HihisentList) > 0 {
		for _, e := range m.HihisentList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.HohosentList) > 0 {
		for _, e := range m.HohosentList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.HahaList) > 0 {
		for _, e := range m.HahaList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.HihiList) > 0 {
		for _, e := range m.HihiList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.HohoList) > 0 {
		for _, e := range m.HohoList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PortId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PortId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HahasentList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HahasentList = append(m.HahasentList, &Hahasent{})
			if err := m.HahasentList[len(m.HahasentList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HihisentList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HihisentList = append(m.HihisentList, &Hihisent{})
			if err := m.HihisentList[len(m.HihisentList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HohosentList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HohosentList = append(m.HohosentList, &Hohosent{})
			if err := m.HohosentList[len(m.HohosentList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HahaList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HahaList = append(m.HahaList, &Haha{})
			if err := m.HahaList[len(m.HahaList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HihiList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HihiList = append(m.HihiList, &Hihi{})
			if err := m.HihiList[len(m.HihiList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HohoList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HohoList = append(m.HohoList, &Hoho{})
			if err := m.HohoList[len(m.HohoList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
